services:
  backend:
    image: kimgyuill/jeonse-ive:latest
    container_name: jeonse-ive-spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - backend

  db:
    image: postgres:15
    container_name: jeonse-ive-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jeonse-ive
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: jeonse-ive-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
