spring:
  profiles:
    active: dev  # 기본값: dev, 배포 시 prod로 오버라이드

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api-docs-ui

management:
  endpoints:
    web:
      exposure:
        include: health


kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
