spring:
  datasource:
    url: jdbc:postgresql://jeonse-ive-db:5432/jeonse-ive
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate  # 운영환경에서는 validate 또는 none 권장
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: info
