spring:
  datasource:
    url: jdbc:postgresql://jeonse-ive-db:5432/jeonse-ive
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  jwt:
    secret: ${JWT_SECRET_KEY}
    access-token-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

  jpa:
    hibernate:
      ddl-auto: validate  # 운영환경에서는 validate 또는 none 권장
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: info
