name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.180.157.93 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ec2-user@54.180.157.93 <<'EOF'
            set -e  # 실패 시 중단

            cd Jeonse-ive-BE

            echo " Pull latest code"
            git pull origin main

            echo "🛠 Build project"
            chmod +x ./gradlew &&
            ./gradlew clean build -x test

            echo " Restart Docker"
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml --env-file .env up --build -d

            echo "🚀 Deployment complete!"
          EOF
